### ISSUE TITLE
Extend documentation of installation ?

### ISSUE THREAD

**Issue by henkvancann** [THCLab/dkms-demo-android#1]
I've forked dkms-demo to my gihub account,  git cloned it on a MacOS system (host machine)
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,1
  Processor Name:	8-Core Intel Core i9
  Processor Speed:	2,3 GHz

Readme.md rather comprehensive. -> Could we do this a bit more elaborate (I could help with PR if you help me get through the installation)

## Step 1 Infrastructure

> Instruction says : 
> HOST_IP_ADDR=\<ip addr of the host machine\> docker-compose up

I did set the ENV variable to my internal IP address of the host machine. Checked 'ENV' command: HOST_IP_ADDR=192.168.1.123

cd into 'infrastructure' directory
'docker-compose up'

hvc@Henks-Mbp20 infrastructure % docker-compose up
Docker Compose is now in the Docker CLI, try `docker compose up`

### Terminal output
Creating network "infrastructure_default" with the default driver
Pulling witness1 (humancolossus/keriox-witness:0.0.4)...
0.0.4: Pulling from humancolossus/keriox-witness
c32ce6654453: Pull complete
94a8bbf380a1: Pull complete
de26e3d5ce13: Pull complete
38c91fa407ce: Pull complete
Digest: sha256:0a989a8b0cc58ddca7391176d5193d2a2c265a8c77e46759033edf691048ea29
Status: Downloaded newer image for humancolossus/keriox-witness:0.0.4
Pulling watcher (humancolossus/keriox-watcher:0.0.4)...
0.0.4: Pulling from humancolossus/keriox-watcher
c32ce6654453: Already exists
94a8bbf380a1: Already exists
61c9cbe6b154: Pull complete
49ec098119c1: Pull complete
Digest: sha256:2beda42cc04b198b28c3c724aed49fb29505dfc3963a323b90775ffb9cae327b
Status: Downloaded newer image for humancolossus/keriox-watcher:0.0.4
Creating infrastructure_witness3_1 ... done
Creating infrastructure_witness1_1 ... done
Creating infrastructure_witness2_1 ... done
Creating infrastructure_watcher_1  ... done
Attaching to infrastructure_watcher_1, infrastructure_witness3_1, infrastructure_witness2_1, infrastructure_witness1_1
watcher_1   | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: EmptyHost', src/bin/watcher-binary.rs:47:65
watcher_1   | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
witness2_1  | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: EmptyHost', src/bin/witness-binary.rs:46:65
witness2_1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
witness3_1  | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: EmptyHost', src/bin/witness-binary.rs:46:65
witness3_1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
witness1_1  | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: EmptyHost', src/bin/witness-binary.rs:46:65
witness1_1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
infrastructure_watcher_1 exited with code 101
infrastructure_witness3_1 exited with code 101
infrastructure_witness2_1 exited with code 101
infrastructure_witness1_1 exited with code 101

### Checks
hvc@Henks-Mbp20 infrastructure % di ls            
REPOSITORY                           TAG        IMAGE ID       CREATED         SIZE
keripy                               v0.6       a46e32ae4967   2 days ago      1.03GB
humancolossus/keriox-witness         0.0.4      4bc83bc5f165   4 weeks ago     87MB
humancolossus/keriox-watcher         0.0.4      1c93bc986e68   4 weeks ago     92.2MB
hvc@Henks-Mbp20 infrastructure % dc ps -all
CONTAINER ID   IMAGE                                COMMAND                  CREATED         STATUS                       PORTS     NAMES
c778e94fc987   humancolossus/keriox-watcher:0.0.4   "/usr/local/bin/watc…"   7 minutes ago   Exited (101) 7 minutes ago             infrastructure_watcher_1

## Step 2 Watcher

> Instruction says : 
> 'WATCHER_HOST=\<watcher host\> docker-compose up'

### Question: what do you mean with this? A name? An IP-address? ...

This is how far I got. I can't make any further sense of it (I maybe could, but I a am lazy demo user). Do you want me to cd into subdirectories (Most probably, but no instructions to do so)? etc.

Please be more extensive and specific :)

**Comment by blelump** [comment]
Hi Henk,

sorry for a late reply. The `WATCHER_HOST` specifies the IP address upon which the witnesses/watcher network will be exposed. They need to be resolvable in your (local) network as they'll communicate with your device, mobile specifically. So as the demo says, `scan QR code`, this in essence contains this IP address, where the Watcher is accessible, so where you as a controller (from the mobile app), are able to communicate with watcher.

The `WATCHER_HOST` var shall be set to whatever IP address your laptop has got from the router in your local network.

As a one liner, you can do it like this: `WATCHER_HOST=<here comes your local IP address> docker compose up`

Let me know if it helps.

**Comment by henkvancann** [comment]
For the purpose of creating better, more elaborate documentation (and not to tell people off) I describe my experience with it:

 a. "So as the demo says, scan QR code, this in essence contains this IP address" -> It does say so, maybe, but.... the sequence isn't right, when I follow the instruction, I get stuck earlier. Review the order of the bullet list?
 
b. See the attachment after having scanned the QR code. And maybe add description that you need to login into GitHub to be able to download the app? Or is something else going on? I'd say don't make the user think over things that should be straight forward.
![signal-2022-06-28-115018](https://user-images.githubusercontent.com/479356/176181363-d41ff42a-c7ba-40e5-9d31-2eabe2e2a35e.jpeg)

 I'll report the issues that I encounter here, so your team could pimp an installation description.

**Comment by blelump** [comment]
Thanks for your time Henk!

There are actually 4 QR codes that need to be scanned.

1. QR you scan to get the app on your mobile https://github.com/THCLab/dkms-demo/tree/main/controller2_mobile_app  (link fixed)
2. QR you scan as soon as you have the app installed.This is 4th point from https://github.com/THCLab/dkms-demo#usage 
3. QR you scan as 5th step in https://github.com/THCLab/dkms-demo#usage 
4. QR you scan as 6th step in https://github.com/THCLab/dkms-demo#usage 

I have refined a bit the steps in the usage section. Let me know if it helps. We can also hop on zoom and try to clarify it.

**Comment by henkvancann** [comment]
hop on zoom and try to clarify it -> Nope, that would be accepting defeat :) I am here to get through the documentation and if necessary I'll try and help to extend  / clarify

**Comment by henkvancann** [comment]
I've worked another hour on your description to get it going :) 

You guys really have to learn and teach yourself to be FAR MORE VERBOSE (yes, in capital letters). It's a guessing game for people that are not informed insiders, like me. And I'm an insider that really wants to get it going. I can tell you: no one will ever going to succeed to install and operate this demo. Not because it's not good. But because it's not documented properly at all. I hope you take no offence, sometime the truth must be told.

Here you have my pull request for one of the README.md files: [pull request](https://github.com/THCLab/dkms-demo/pull/2). Have a look to see what I mean. Be more verbose, for example speak out loud what you do, record what you say, and have it in written text afterwards and add the screen recording. Just my two cents.

I suggest you only leave one README.md file on your directory tree, because it's confusing to have more than one README.md, each in every subdirectory. I recommend to give them good explanatory names like 'install-and-compile-the-android-app.md'.

**Comment by blelump** [comment]
We probably assume too much ;-) . Thanks for your comment. I'll close this issue now and lets continue in a more granular issues if needed.
