### ISSUE TITLE
Filenames descriptive?!

### ISSUE THREAD

**Issue by henkvancann** [THCLab/dkms-demo-android#5]
I suggest you only leave one README.md file on your directory tree, because it's confusing to have more than one README.md, each in every subdirectory? 
I recommend to give them good explanatory names like 'install-and-compile-the-android-app.md'.

**Comment by blelump** [comment]
What exactly do you have in mind? The idea behind README's in sub dirs is that you discover what to do as you go. More or less like knowledge base where information is structured as a tree.

**Comment by henkvancann** [comment]
A matter of taste. To edit this tree of README's you see multiple README-files in your IDE open and wonder which is which. But never mind.
